
server:
  port: 11060
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  application:
    name: authentication

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.112.243.126:3306/technologyTransaction?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: ZMHYRJ@002
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
  main:
    allow-bean-definition-overriding: true
  security:
    permit:
      ant-matchers:
        - /users/login
        - /sys/role/getRoles
        - /users/checkToken
        - /users/clearToken
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: /mapper/*Mapper.xml
  typeAliasesPackage: com.itts
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



