spring:
  cloud:
    nacos:
      discovery:
        server-addr: 172.21.25.8:1884
  # Zipkin配置
  zipkin:
    base-url: http://172.21.25.8:19411/ #zipkin server的请求地址
    discovery-client-enabled: false #让nacos把它当成一个URL， 而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比
  application:
    name: gateway
#  main:
#    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO
