server:
  port: 11900

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18848
    gateway:
      #开启网关拉取nacos的服务
      discovery:
        locator:
          enabled: true
      routes:
        - id: technology_transfer_route                       #路由的ID，没有固定规则但要求唯一
          uri: lb://technology-transaction-service           #匹配后提供服务的路由地址
          predicates:
            - Path=/technology_transaction/**             #断言，路径相匹配的进行路由
          filters: #过滤器，请求在传递过程中通过过滤器修改
            - StripPrefix=1                              #去掉第一层前缀，转发给后续的路径

        - id: payment_route                       #路由的ID，没有固定规则但要求唯一
          uri: lb://payment-service          #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/**             #断言，路径相匹配的进行路由
          filters: #过滤器，请求在传递过程中通过过滤器修改
            - StripPrefix=1                              #去掉第一层前缀，转发给后续的路径
  # Zipkin配置
  zipkin:
    base-url: http://localhost:19411/ #zipkin server的请求地址
    discovery-client-enabled: false #让nacos把它当成一个URL， 而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比
  application:
    name: gateway
#  main:
#    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

#设置日志级别,ERROR/WARN/INFO/DEBUG,默认是INFO以上才显示
logging:
  level:
    root: INFO
