server:
  port: 11004

spring:
  profiles:
    active: dev
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allow-credentials: true
            allowedOrigins: "*"
            allowed-headers: "*"
            allowedMethods: "*"
            max-age: 3600
      #开启网关拉取nacos的服务
      discovery:
        locator:
          enabled: true
      routes:
        # 技术交易服务
        - id: technology_transfer_route                       #路由的ID，没有固定规则但要求唯一
          uri: lb://technology-transaction-service           #匹配后提供服务的路由地址
          predicates:
            - Path=/technology_transaction/**             #断言，路径相匹配的进行路由
          filters: #过滤器，请求在传递过程中通过过滤器修改
            - StripPrefix=1                              #去掉第一层前缀，转发给后续的路径

        # 支付服务
        - id: payment_route                       #路由的ID，没有固定规则但要求唯一
          uri: lb://payment-service          #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/**             #断言，路径相匹配的进行路由
          filters: #过滤器，请求在传递过程中通过过滤器修改
            - StripPrefix=1                              #去掉第一层前缀，转发给后续的路径

        # 用户服务
        - id: user_route                       #路由的ID，没有固定规则但要求唯一
          uri: lb://user-service          #匹配后提供服务的路由地址
          predicates:
            - Path=/user/**             #断言，路径相匹配的进行路由
          filters: #过滤器，请求在传递过程中通过过滤器修改
            - StripPrefix=1                              #去掉第一层前缀，转发给后续的路径

        # 人才培养服务
        - id: personnel_route                       #路由的ID，没有固定规则但要求唯一
          uri: lb://person-training-service          #匹配后提供服务的路由地址
          predicates:
            - Path=/personnel_training/**             #断言，路径相匹配的进行路由
          filters: #过滤器，请求在传递过程中通过过滤器修改
            - StripPrefix=1                              #去掉第一层前缀，转发给后续的路径