# 配置端口号
server:
  port: 11060
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:18848
  # Redis 配置
  redis:
    # Redis 服务器地址
    host: 120.26.184.41
    # 连接端口号
    port: 6379
    # 数据库索引（0 - 15）
    database: 0
    # 超时时间（毫秒）
    timeout: 10000
    # lettuce 参数
    lettuce:
      pool:
        # 最大连接数(使用负值表示没有限制) 默认为 8
        max-active: 10
        # 最大阻塞等待时间(使用负值表示没有限制) 默认为 -1 ms
        max-wait: -1
        # 最大空闲连接 默认为 8
        max-idle: 5
        # 最小空闲连接 默认为 0
        min-idle: 0
  # Zipkin配置
  zipkin:
    base-url: http://localhost:19411/ #zipkin server的请求地址
    discovery-client-enabled: false #让nacos把它当成一个URL， 而不要当做服务名
  sleuth:
    sampler:
      probability: 1.0 #采样的百分比