# 配置端口号
server:
  port: 11060
spring:
  application:
    name: payment-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: test
  # 配置国际化，basename 指定国际化文件前缀
  messages:
    basename: static/i18n/messages
    encoding: UTF-8
  # 设置 json 中日期显示格式
  jackson:
    # 设置显示格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 设置时区
    time-zone: GMT+8

#订单支付消息队列配置
mqconfig:
  #延迟队列，不能被监听消费
  order_release_delay_queue: order.release.delay.queue
  #延迟队列的消息过期后转发的队列
  order_release_queue: order.release.queue
  #交换机
  order_event_exchange: order.event.exchange
  #进入延迟队列的路由key
  order_release_delay_routing_key: order.release.delay.routing.key
  #消息过期，进入释放死信队列的key
  order_release_routing_key: order.release.routing.key
  #消息过期时间,毫秒,15分钟
  ttl: 900000