# 配置端口号
server:
  port: 11060
spring:
  # Redis 配置
  redis:
    # Redis 服务器地址
    host: 127.0.0.1
    # 连接端口号
    port: 6379
    # 数据库索引（0 - 15）
    database: 0
    # 超时时间（毫秒）
    timeout: 10000
    # lettuce 参数
    lettuce:
      pool:
        # 最大连接数(使用负值表示没有限制) 默认为 8
        max-active: 10
        # 最大阻塞等待时间(使用负值表示没有限制) 默认为 -1 ms
        max-wait: -1
        # 最大空闲连接 默认为 8
        max-idle: 5
        # 最小空闲连接 默认为 0
        min-idle: 0