# 配置端口号
server:
  port: 11070
task:
  pool:
    # 核心线程池大小
    core-pool-size: 10
    # 最大线程数
    max-pool-size: 30
    # 活跃时间
    keep-alive-seconds: 60
    # 队列容量
    queue-capacity: 50
# 阿里云配置信息
aliyun:
  # common 配置信息
  accessKeyId: LTAI4GEWZbLZocBzXKYEfmmq
  accessKeySecret: rZLsruKxWex2qGYVA3UsuBgW5B3uJQ
  # OSS 相关配置信息
  endPoint: http://oss-cn-beijing.aliyuncs.com
  bucketName: admin-vue-template
  domain: http://admin-vue-template.oss-cn-beijing.aliyuncs.com
  # SMS 短信服务
  regionId: cn-hangzhou
  signName: 后台管理系统
  templateCode: SMS_194050461
spring:
  application:
    name: user-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: /mapper/*Mapper.xml
  typeAliasesPackage: com.itts
#分页pageHelper
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
# huawei ods
huawei:
  obs:
    ak: D19EMDG2HD30LAAJULFV
    sk: Oy26kRatswkUvkhhKQNyQdhDZxwT3MNExtwcFoae
    # 桶
    bucketName: cdspzb
    upload:
      endPoint: obs.cn-north-4.myhuaweicloud.com
  # 访问的endPoint
    access:
      endPoint: cdspzb.obs.cn-north-4.myhuaweicloud.com

ribbon:
  ConnectTimeout: 10000 # ribbon链接超时时长
  ReadTimeout: 10000 # ribbon读取超时时间长
