# 配置端口号
server:
  port: 11060
spring:
  application:
    name: web-crawler-service
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: test
  # 配置国际化，basename 指定国际化文件前缀
  messages:
    basename: static/i18n/messages
    encoding: UTF-8
  # 设置 json 中日期显示格式
  jackson:
    # 设置显示格式
    date-format: yyyy-MM-dd HH:mm:ss
    # 设置时区
    time-zone: GMT+8
